spring:
  application:
    name: logging

management:
  tracing:
    sampling:
      probability: 1.0  # ?? ?? ??

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    io.micrometer.tracing: DEBUG
